Add rebuild script for psql2 test server
enlyze/postgres-upgrade-automation pull request #1
Opened 2023-05-24 13:04 UTC by daniel-k

The script stops the Postgres cluster, restores the Postgres data dir from a backup in the volume and then rebuild the server from a snapshot.

2023-05-24 13:49 UTC, muattiyah requested changes
Let's abstract away the postgres versions like the other script(s).

2023-05-24 13:49 UTC, muattiyah commented on psql2-rebuild.py
> +    assert public_ip != "116.203.98.196", "Don't ever run this on psql2!"
Let's please put the IP in a "constant" with a descriptive name. Also, let's not use `assert` except in tests.

2023-05-24 14:33 UTC, daniel-k commented
> Let's abstract away the postgres versions like the other script(s).

21825d6

2023-05-24 14:33 UTC, daniel-k commented on psql2-rebuild.py
> +    assert public_ip != "116.203.98.196", "Don't ever run this on psql2!"
d3a9c29

2023-05-24 14:50 UTC, muattiyah requested changes

2023-05-24 14:50 UTC, muattiyah commented on psql2-rebuild.py
> +    for service in get_running_postgres_cluster_services(c):
Why are we doing this generically like this? Where the context is that we're upgrading from 1 postgres version to another, so we can pass the versions as CLI arguments like in the other script.

2023-05-24 14:52 UTC, daniel-k commented on psql2-rebuild.py
> +    for service in get_running_postgres_cluster_services(c):
This script is not (exclusively) meant to rebuild the test server for major version upgrades. It will serve for testing TimescaleDB extension updates as well. Those are independent of Postgres major versions.

2023-05-24 15:49 UTC, daniel-k commented on psql2-rebuild.py
> +    for service in get_running_postgres_cluster_services(c):
Sorry, I don't follow. This script does not upgrade anything. Apart from that. the state the test server is in isn't very well defined either, so for now it's a manual exercise to create a test server together with a volume that has a recent snapshot of the data. 

I feel like your comment should be on the timescale upgrade script, which can be found [here](https://github.com/enlyze/postgres-upgrade-automation/blob/main/psql2-timescale.py).

2023-05-24 15:52 UTC, muattiyah commented on psql2-rebuild.py
> +    for service in get_running_postgres_cluster_services(c):
> Sorry, I don't follow. This script does not upgrade anything. 

It is used in a context where we're upgrading things. I'd rather the postgresql we're working with at the time be dynamic and explicitly passed.

2023-05-30 14:31 UTC, daniel-k commented on psql2-rebuild.py
> +    for service in get_running_postgres_cluster_services(c):
This more or less turned into a rewrite, but it's much less hardcoding now and rebuilding the server should be quite convenient now. Please check out 7b63bde or rather look at the complete diff of the PR again :)

2023-05-31 06:19 UTC, muattiyah requested changes

2023-05-31 06:19 UTC, muattiyah commented on psql2-rebuild.py
> +        raise Exception(f"Backup dir '{backup_dir}' already exists")
This can be a `FileExistsError`.

2023-05-31 06:19 UTC, muattiyah commented on psql2-rebuild.py
> +        raise Exception(f"Postgres {version} cluster '{cluster}' not found")
This can be a `NotADirectoryError`.

2023-05-31 06:19 UTC, muattiyah commented on psql2-rebuild.py
> +        raise Exception(f"Postgres {version} cluster '{cluster}' not found")
Same as in the previous function and the next function, should be DRYed up.

2023-05-31 06:19 UTC, muattiyah commented on psql2-rebuild.py
> +    parser.add_argument("postgres_version", type=int)
What would be the situation if we have multiple databases with the same major version and different minor versions?

2023-05-31 06:19 UTC, muattiyah commented on psql2-rebuild.py
> +        raise Exception(f"Couldn't find server '{TEST_SERVER_NAME}' at Hetzner")
Maybe a `ConnectionError` is a better fit here?

2023-05-31 06:19 UTC, muattiyah commented on psql2-rebuild.py
> +            Action.DESTROY: partial(delete_image, image),
OCD, can we have these in the same order as the other target? i.e. (CREATE, DESTROY, RESTORE)

2023-05-31 07:07 UTC, daniel-k commented on psql2-rebuild.py
> +    parser.add_argument("postgres_version", type=int)
I don't think that's possible. In our scripts we are assuming to deal with standard Debian packaged Postgres that uses the `pg_cluster*` wrappers.

2023-05-31 07:11 UTC, daniel-k commented on automation_utils.py
> +    if not result.ok and not kwargs.get("warn", False):
1cc587044201c3e851cb75888fb272b07048fa36

2023-05-31 07:11 UTC, daniel-k commented on automation_utils.py
> +    res = run(c, f"stat {path}", hide=True, warn=True)
bcc1afec9d623e2721373ab332c8514eecba15d7

2023-05-31 07:12 UTC, daniel-k commented on automation_utils.py
> +    res = run(c, f"stat {path}", hide=True, warn=True)
Not anymore, see 1cc587044201c3e851cb75888fb272b07048fa36

2023-05-31 07:13 UTC, daniel-k commented on psql2-rebuild.py
> +            Action.DESTROY: partial(delete_image, image),
e8d7aea

2023-05-31 07:27 UTC, daniel-k commented on psql2-rebuild.py
> +from postgres import get_postgres_data_and_backup_dir
Whoopsie :innocent: Good catch! f55764783c42254158f2cb4f3b75b9d399f38bb0

2023-05-31 07:27 UTC, daniel-k commented on psql2-rebuild.py
> +        raise Exception(f"Postgres {version} cluster '{cluster}' not found")
f8d6d47ebbbc7449ee3e5b65421716ad10e18777

2023-05-31 07:32 UTC, daniel-k commented on psql2-rebuild.py
> +        raise Exception(f"Couldn't find server '{TEST_SERVER_NAME}' at Hetzner")
I went with a `LookupError`: 3057ff8

2023-05-31 07:34 UTC, daniel-k commented on psql2-rebuild.py
> +        raise Exception(f"Postgres {version} cluster '{cluster}' not found")
`NotADirectoryError` is for operations that only work on directories but you gave it e.g. a file. I've turned it into a lookup error (since we're looking up a postgres cluster) after refactoring.

2023-05-31 07:34 UTC, daniel-k commented on psql2-rebuild.py
> +        raise Exception(f"Backup dir '{backup_dir}' already exists")
3057ff8

2023-05-31 09:14 UTC, muattiyah requested changes
A couple of minor things.

2023-05-31 09:14 UTC, muattiyah commented on automation_utils.py
> +        raise ChildProcessError (f"Command {cmd} failed with exit code {result.exited}")
```suggestion
        raise ChildProcessError(f"Command {cmd} failed with exit code {result.exited}")
```

2023-05-31 09:14 UTC, muattiyah commented on postgres.py
> +    ]
Where is this used?

2023-05-31 10:12 UTC, daniel-k commented on postgres.py
> +    ]
It has been used in code that has already been refactored. I've removed it for now and keep it locally, you never know. ce96247327f1dbd1df221619f0a72024a4231798

2023-05-31 10:13 UTC, muattiyah commented on postgres.py
> +    ]
Well, it's in the log of this PR :)

2023-05-31 10:14 UTC, muattiyah approved these changes

2023-05-31 10:15 UTC, merged